---
apiVersion: v1
kind: Namespace
metadata:
  name: fleetlock
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetlock-config
  namespace: fleetlock
  labels:
    app: fleetlock
data:
  config.yaml: |
    ---
    logLevel: info
    storage:
      type: kubernetes
    groups:
      default:
        slots: 1
      master:
        slots: 1
      worker:
        slots: 1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleetlock
  namespace: fleetlock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleetlock-leases
  namespace: fleetlock
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleetlock-leases
  namespace: fleetlock
subjects:
  - kind: ServiceAccount
    name: fleetlock
roleRef:
  kind: Role
  name: fleetlock-leases
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetlock
  namespace: fleetlock
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleetlock
  namespace: fleetlock
subjects:
  - kind: ServiceAccount
    name: fleetlock
    namespace: fleetlock
roleRef:
  kind: ClusterRole
  name: fleetlock
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app: fleetlock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetlock
  template:
    metadata:
      labels:
        app: fleetlock
    spec:
      serviceAccountName: fleetlock
      containers:
        - name: fleetlock
          image: ghcr.io/heathcliff26/fleetlock:latest
          args:
            - "-c"
            - "/config/config.yaml"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /config
              name: fleetlock-config
      volumes:
        - name: fleetlock-config
          configMap:
            name: fleetlock-config
---
apiVersion: v1
kind: Service
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app: fleetlock
spec:
  selector:
    app: fleetlock
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleetlock
  namespace: fleetlock
  labels:
    app: fleetlock
spec:
  rules:
    - host: fleetlock.example.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleetlock
                port:
                  name: http
