---
# The level of loggin output
logLevel: info

server:
  # The listen address of the server in the form of <ip>:<port>
  listen: ":8080"
  ssl:
    # Enable ssl
    enabled: false
    # ssl certificate
    cert: ""
    # ssl private key
    key: ""

storage:
  # The storage backend to use
  #
  # Options:
  #   memory:     Ephemeral, not recommended for production
  #   sqlite:     Persistent, does not really support High Availability
  #   postgres:   Use postgres database
  #   mysql:      Use mysql database
  #   redis:      Use redis database
  #   etcd:       Use etcd database
  #   kubernetes: Use kubernetes leases
  #
  # Default: memory
  #
  type: memory
  sqlite:
    # The file to use for storing the database
    file: test.db
  postgres:
    # The address of the database
    address: "localhost:26257"
    # The username and password for login
    username: ""
    password: ""
    # The database name
    database: ""
    # Additional options for connections. Will be appended with ?
    options: ""
  mysql:
    # The address of the database
    address: "tcp(localhost:3306)"
    # The username and password for login
    username: ""
    password: ""
    # The database name
    database: ""
    # Additional options for connections. Will be appended with ?
    options: ""
  redis:
    # The address of the redis database
    address: "localhost:1234"
    # (Optional) List of addresses when connectiong should be loadbalanced between active-active replicas.
    addresses:
      - ""
    # (Optional) Username for authentication
    username: ""
    # (Optional) Password for authentication
    password: ""
    # (Optional) Database to use
    db: 0
    # (Optional) Use TLS when connecting to database
    tls: false
    # (Optional) Sentinel optiones
    sentinel:
      # Enable sentinel
      enabled: false
      # Master name
      master: ""
      # Addresses for sentinel server
      addresses:
        - ""
      # (Optional) Username for authentication with sentinel
      username: ""
      # (Optional) Password for authentication with sentinel
      password: ""
  etcd:
    # The etcd endpoints
    endpoints:
      - "localhost:2379"
    # (Optional) Username for authentication
    username: ""
    # (Optional) Password for authentication
    password: ""
    # (Optional) Client certificate for authentication
    cert: ""
    # (Optional) Private key of client certificate for authentication
    key: ""
  kubernetes:
    # (Optional) Path to kubeconfig file, default uses in-cluster serviceaccount
    kubeconfig: ""
    # (Optional) Namespace to create leases in, default reads it from file inside pod or defaults to fleetlock
    namespace: ""

# The configured groups to serve, when it isn't defined here, it is not accepted.
#
# Format:
#   <name>:
#     slots: int
#
# When empty, it uses the default group with 1 slot
#
groups:
  default:
    # Number of slots that can be reserved simoultanously by clients
    slots: 1
