---
# The level of loggin output
logLevel: info

server:
  # The listen address of the server in the form of <ip>:<port>
  listen: ":8080"
  ssl:
    # Enable ssl
    enabled: false
    # ssl certificate
    cert: ""
    # ssl private key
    key: ""

storage:
  # The storage backend to use
  #
  # Options:
  #   memory: Ephemeral, not recommended for production
  #   sqlite: Persistent, does not really support High Availability
  #   redis: Use redis database
  #
  # Default: memory
  #
  type: memory
  sqlite:
    # The file to use for storing the database
    file: test.db
  redis:
    # The address of the redis database
    address: "localhost:1234"
    # (Optional) Username for authentication
    username: ""
    # (Optional) Password for authentication
    password: ""
    # (Optional) Database to use
    db: 0
    # (Optional) Sentinel optiones
    sentinel:
      # Enable sentinel
      enabled: false
      # Master name
      master: ""
      # Addresses for sentinel server
      addresses:
        - ""
      # (Optional) Username for authentication with sentinel
      username: ""
      # (Optional) Password for authentication with sentinel
      password: ""

# The configured groups to serve, when it isn't defined here, it is not accepted.
#
# Format:
#   <name>:
#     slots: int
#
# When empty, it uses the default group with 1 slot
#
groups:
  default:
    # Number of slots that can be reserved simoultanously by clients
    slots: 1
