---
name: CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Use to set tag, default: rolling"
        type: string
        default: "rolling"
        required: false
      dry-run:
        description: "Do not push image"
        type: boolean
        default: false
        required: false
  push:
    branches: ["main"]
    paths:
      - "go.mod"
      - "go.sum"
      - "*.go"
      - "**/*.go"
      - "Dockerfile"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  lint:
    uses: heathcliff26/ci/.github/workflows/golang-lint.yaml@main

  build:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    needs:
      - lint
    permissions:
      contents: read
      packages: write
    with:
      dockerfile: Dockerfile
      tag: "${{ github.event.inputs.tag }}"
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' || github.event.inputs.dry-run == 'true' }}
      build-args: "RELEASE_VERSION=${{ github.event.inputs.tag }}"
    secrets: inherit
